server {
    listen 80;
    server_name  ${DOMAIN};
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen       443 ssl http2;
    server_name  ${DOMAIN};
    ssl_certificate     /etc/ssl/${DOMAIN}/${DOMAIN}.pem;
    ssl_certificate_key /etc/ssl/${DOMAIN}/${DOMAIN}.key;
    include      snippets/ssl.conf;

    location / {

        index  index.html;
        root ${INDEX_PATH}
        include     snippets/proxy.conf;
        return try_files $uri $uri/ =404;
    }

    location /line-bot {
        include     snippets/proxy.conf;
        proxy_pass  http://${PRIVATE_IP}:${PORT}/${ROUTE};
    }
}